name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  verify:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: p@ss@dmin
          POSTGRES_DB: payments_system_test
        ports:
          - 5432:5432

        options: >-
          --health-cmd "pg_isready -U admin -d payments_system_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: npm

      - name: Clean Install Dependencies
        run: npm ci

      - name: Typecheck
        run: npm run check-types

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Tests
        run: npm run test
